
services:
  db:
    image: postgres:17
    container_name: projet_universite_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: projet_universite
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: projet_universite_backend
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/projet_universite
      - NODE_ENV=production
      - SNCF_API_KEY=794cbefe-7238-4c7c-835c-8e16aa6f3d7f
    depends_on:
      - db
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    image: node:18
    container_name: projet_universite_frontend
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
